# this file does not affect the conda-forge build, only the local repos github actions
# (in particular running unit tests)
c_stdlib:
- sysroot # [linux]
- macosx_deployment_target # [osx]
c_stdlib_version:
- '2.17' # [linux]
- '14.5' # [osx]
python:
- '3.9'
- '3.10'
- '3.11'
- '3.12'
- '3.13'

numpy:
  - 2 # [py>=313]